project:
  title: "I CIMCYC Workshop on Learning and Attention"
  type: website
  output-dir: docs

website:
  favicon: "images/icon.png"
  search: false
  description: "The I CIMCYC workshop on Learning and Attention offers an afternoon of talks and discussion on how learning and attention shape human cognition and behavior. The aim is to bring together students and researchers interested in these topics and to provide an accessible but research-oriented overview of current work in the field."
  navbar:
    left:
      - href: index.qmd#seminario
        text: About
      - href: index.qmd#speakers
        text: Talks
      - href: index.qmd#programme
        text: Programme
      - href: index.qmd#inscripcion
        text: Registration
      - href: index.qmd#venue
        text: Venue
      - href: index.qmd#faculty
        text: Organizers

  page-footer:  
    left: >-
      &#169; 2025, Francisco Garre-Frutos
    right: >-
      <span class="faux-block">Made with {{< fa brands r-project >}}, ChatGPT, and [Quarto](https://quarto.org/)</span><br>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub](https://github.com/franfrutos/learning_attention_workshop)</span>
      

format:
  html:
    theme:
      light: [journal, styles.scss]
      dark: [journal, styles-dark.scss]
    toggle:
      icon: "circle-half"
      placement: "navbar"
    toc: false
    smooth-scroll: true
    page-layout: article
    grid:
      margin-width: 320px 
      
filters:
  - fontawesome
  - academicons
